# NumPy

Why Numpy?  
Numpy is faster

In [2]:
# Importando biblioteca Numpy e renomeando como np 
import numpy as np 

In [3]:
a = np.array([1,2,3,4,5]) # passando como uma lista
b = np.array((2.2,4.2,6.2)) # passando como uma tupla 
print(a, type(a), a.dtype)
print(b, type(b), b.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
[2.2 4.2 6.2] <class 'numpy.ndarray'> float64


## Numpy (Dimensions)

In [4]:
a = np.array([[1,2,3],[3,4,5]]) # declarando um array de duas dimensões obs: para se considerar duas dimensões, os arrays precisam ter o mesmo tamanho
print(a.ndim) # imprimindo quantas dimensões o array a possui
c = np.array([[1,2,3],[1,2,3,4]]) # array unidimensional, são 2, mas tem tamanhos diferentes 
print(b.ndim)
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # declarando um array tridimensioal, # 1 2 3  / 7 8 9
print(d.ndim)                                                                               # 4 5 6 /  10 11 12           
print(d.shape) #numero de conjunto de arrays bidimencionais, quantos arrays existem em cada conjunto, quantos elementos existem em cada array 

2
1
3
(2, 2, 3)


/tmp/ipykernel_352/1151873454.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = np.array([[1,2,3],[1,2,3,4]]) # array unidimensional, são 2, mas tem tamanhos diferentes


In [5]:
# acessando valores de um array bidimensional
print(a[0,1]) # primeiro array, index 1. obs: lembrar que a primeira posição do array é 0 
# acessando valores de um array tridimensional 
print(d[1,1,2]) # segundo conjunto de arrays, segundo array, terceira posição  

2
12


## Userful Functions Numpy 
1. np.arange -> cria arrays ordenados 
2. np.random.permutation ->  reoderna lista de forma aleatória
3. np.reshape -> modela lista de dados em uma matriz

In [6]:
A = np.arange(20,100,3) # cria um array de 20 a 100, somando 3 
print(A)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [7]:
A = np.random.permutation(np.arange(10))
print(A)
print(np.random.randint(20,30)) # função np.random.randint -> gera um número aleatório a partir de um determinado intervado 

[4 9 1 3 7 6 0 2 5 8]
27


In [8]:
D = np.arange(10)
print(D.reshape(2,5)) # cria uma matriz com 2 linhas e 5 colunas obs: precisam ser multiplas do numero de elementos
print('--------')
C = np.arange(8).reshape(2,2,2) # cria uma matriz bidimensional 2x2x2
print(C)

[[0 1 2 3 4]
 [5 6 7 8 9]]
--------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## Slicing Numpy
recortar valores de um intervalo em uma lista ou matriz

In [9]:
A = np.arange(50)
b = A[40:50]  # recortando valores entre 40 e 50 
print('Valor b:',b)
b[0] = 999 # mudando elemento da lista b 
print('Valor A:',A)  # também é alterado na lista A 

# Para essa mudança não ocorrer também na lista principal: 
b = A[40:50].copy() # utilizar a função copy
b[0] = 888
print('Valor b:',b) 
print('Valor A:',A)

Valor b: [40 41 42 43 44 45 46 47 48 49]
Valor A: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39 999  41  42  43  44  45  46  47  48  49]
Valor b: [888  41  42  43  44  45  46  47  48  49]
Valor A: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39 999  41  42  43  44  45  46  47  48  49]


In [10]:
# encontrando o index de algum valor presente na lista 

idx = np.argwhere(A==999) # utilização da função argwhere 
print(idx) # printa na tela o index

[[40]]


In [11]:
C = np.random.permutation(np.arange(8)) 
C.reshape(2,4)

idx = np.argwhere(C==7)
print(idx)

[[1]]


In [12]:
# acessando valores em uma matriz

A = np.arange(25)
A = A.reshape(5,5)
print(A)
print('Imprime elemento:', A[0,0]) # imprime primeiro elemento da matriz. Primeiro parametro é a linha, o segundo é a coluna  
print('Imprime coluna:', A[:,0]) # imprime a primeira coluna  
print('Imprime linha:', A[2,:]) # imprime terceira linha
print('imprime submatrix:\n', A[0:2, 0:2]) # imprime primeira submatrix 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Imprime elemento: 0
Imprime coluna: [ 0  5 10 15 20]
Imprime linha: [10 11 12 13 14]
imprime submatrix:
 [[0 1]
 [5 6]]


## Numpy hstack, vstack, sort(axis=0)

In [13]:
# Checando tempo de do np 
# Sempre que possível utilizar as funções universais no np

B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B) # B.sum() 

94.6 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
575 µs ± 9.34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Pandas 
Pandas foi implementado com Numpy  
**O que é?**  
Pandas é uma biblioteca de software criada para a linguagem Python para manipulação e análise de dados. Em particular, oferece estruturas e operações para manipular tabelas numéricas e séries temporais


In [26]:
# importando biblioteca pandas 

import pandas as pd 

print(pd.__version__) # exibe versão do pandas 
pd.show_versions()  # exibe as versões de tudo instalado no python 

1.3.4

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.72-microsoft-standard-WSL2
Version          : #1 SMP Wed Oct 28 23:40:43 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.

## Pandas(Series)  
One-dimensional ndarray with axis labels (including time series). Label = Rótulo


In [39]:
weight_dict = {'Joana':50,'Amélia':60,'Francisca':70} # criando um dicionário com pesos kg 
weight = pd.Series(weight_dict) # uso do pandas, os nomes se comportarão como indices, e os números, valores dos seus respectivos indices 

print(weight,'\n') # verificando os valores e indices do array
print(weight['Francisca']) # verificando o valor de um uníco indice 

Joana        50
Amélia       60
Francisca    70
dtype: int64 

70


In [48]:
# Declaração de novo dicionário 

height_dict = {'Joana':1.5, 'Amélia':1.6, 'Francisca': 1.62} 
height = pd.Series(height_dict) 

## Pandas(DataFrame)
Pandas DataFrame é uma estrutura de dados bidimensional com os dados alinhados de forma tabular em linhas e colunas, como uma planilha do excel

In [93]:
df = pd.DataFrame({'Peso': weight, 'Altura': height}) 
df # df.T -> para transpor a tabela

Peso  Altura
Joana        50    1.50
Amélia       60    1.60
Francisca    70    1.62

In [91]:
# acessando valores de DF 

print(df.columns,'\n') # saber quais labels possuem 
print(df.values[0:3,1:3]) # acessando dado especifico, todas as alturas 

Index(['Peso kg', 'Altura'], dtype='object') 

[[1.5 ]
 [1.6 ]
 [1.62]]


In [104]:
# adicionando novo valor ao df 

df['IMC'] = round(df['Peso'] / (df['Altura']**2), 2) # realizando calculo do IMC, delimitando em 2 casas decimais com round()  
df   

print(df[df['IMC'] > 24],'\n') # imprime caso em que o iMC é mairo que 24 
print(df['IMC'] > 24) # retorna true/false para os IMC's maior que 24

           Peso  Altura    IMC
Francisca    70    1.62  26.67 

Joana        False
Amélia       False
Francisca     True
Name: IMC, dtype: bool


## Pandas(NaN)

Como tratar dados faltates   
NaN = Not a Number
De forma básica, os tratos podem ser tratados com duas funções  
1. fillna() - preenche os dados faltantes com 0 
2. dprona  - remove colunas que faltam dados 

In [120]:
age_dict = {'Joana':10, 'Samara':9}  # idade da Maria não foi declarada
food_dict = {'Maria': 'Sorvete', 'Samara': 'carne'} # comida da joana não foi declarada

A = pd.DataFrame([age_dict, food_dict]) # passa data frame como lista 
A 

Joana Samara    Maria
0   10.0      9      NaN
1    NaN  carne  Sorvete

In [122]:
# preenchendo valores com 0 

A.fillna(0)

Joana Samara    Maria
0   10.0      9        0
1    0.0  carne  Sorvete

In [130]:
# exibe apenas linhas/colunas da tabela sem dados nao preechidos

A.dropna(axis = 1) # o parametro axis= determina se será analisado linhas ou colunas 
                 # 1 = colunas, 0 = linhas. Exitem outros parametros muito úteis, conferir documentação  

Samara
0      9
1  carne

## Pandas(CSV Files)

Para rabalhar com datasets reais, é necessário importar dados, como planilhas

In [34]:
# Importando bibliotecas Obs: nesse caso algumas já foram exportadas anteriormente 

import pandas as pd 
import numpy as np 
from sklearn.impute import SimpleImputer # 

In [35]:
# lendo o dataframe 

df = pd.read_csv('Datasets/Dataset Covid19_Kaggle/covid_19_clean_complete.csv') # a função read_csv faz a leitura do arquivo csv 

In [36]:
# visualizando a cabecinha do dataframe

df.head()

Province/State Country/Region       Lat       Long        Date  Confirmed  \
0            NaN    Afghanistan  33.93911  67.709953  2020-01-22          0   
1            NaN        Albania  41.15330  20.168300  2020-01-22          0   
2            NaN        Algeria  28.03390   1.659600  2020-01-22          0   
3            NaN        Andorra  42.50630   1.521800  2020-01-22          0   
4            NaN         Angola -11.20270  17.873900  2020-01-22          0   

   Deaths  Recovered  Active             WHO Region  
0       0          0       0  Eastern Mediterranean  
1       0          0       0                 Europe  
2       0          0       0                 Africa  
3       0          0       0                 Europe  
4       0          0       0                 Africa

In [37]:
# visualisando os ultimos dados

df.tail()

Province/State         Country/Region        Lat       Long        Date  \
49063            NaN  Sao Tome and Principe   0.186400   6.613100  2020-07-27   
49064            NaN                  Yemen  15.552727  48.516388  2020-07-27   
49065            NaN                Comoros -11.645500  43.333300  2020-07-27   
49066            NaN             Tajikistan  38.861000  71.276100  2020-07-27   
49067            NaN                Lesotho -29.610000  28.233600  2020-07-27   

       Confirmed  Deaths  Recovered  Active             WHO Region  
49063        865      14        734     117                 Africa  
49064       1691     483        833     375  Eastern Mediterranean  
49065        354       7        328      19                 Africa  
49066       7235      60       6028    1147                 Europe  
49067        505      12        128     365                 Africa

In [ ]:
# Verificando a coluna 'Province/State', pareciam estar vazias, mas possui 14664 valores. 
# Isso é feito de forma mais eficiente na célula 43 coma a funçãi info 

df['Province/State'].count()

In [38]:
# Removendo a coluna 'Active', não é interessante para a nossa analise por enquanto 
# axis 1 especifica que é uma ação com a coluna, inplace reflete a mudanças no csv na variavel df. 

df.drop(['Active'], axis=1, inplace=True)

In [48]:
# checando se a coluna Active foi excluida 

df.head(10)

Province/State       Country/Region       Lat        Long  \
0                            NA          Afghanistan  33.93911   67.709953   
1                            NA              Albania  41.15330   20.168300   
2                            NA              Algeria  28.03390    1.659600   
3                            NA              Andorra  42.50630    1.521800   
4                            NA               Angola -11.20270   17.873900   
5                            NA  Antigua and Barbuda  17.06080  -61.796400   
6                            NA            Argentina -38.41610  -63.616700   
7                            NA              Armenia  40.06910   45.038200   
8  Australian Capital Territory            Australia -35.47350  149.012400   
9               New South Wales            Australia -33.86880  151.209300   

         Date  Confirmed  Deaths  Recovered             WHO Region  
0  2020-01-22          0       0          0  Eastern Mediterranean  
1  2020-01-22          0       0          0                 Europe  
2  2020-01-22          0       0          0                 Africa  
3  2020-01-22          0       0          0                 Europe  
4  2020-01-22          0       0          0                 Africa  
5  2020-01-22          0       0          0               Americas  
6  2020-01-22          0       0          0               Americas  
7  2020-01-22          0       0          0                 Europe  
8  2020-01-22          0       0          0        Western Pacific  
9  2020-01-22          0       0          0        Western Pacific

In [42]:
# Exibindo algumas informações úteis sobre o dataframe 
# Exibe algumas informações estatísticas básicas 

df.describe()

Lat          Long     Confirmed         Deaths     Recovered
count  49068.000000  49068.000000  4.906800e+04   49068.000000  4.906800e+04
mean      21.433730     23.528236  1.688490e+04     884.179160  7.915713e+03
std       24.950320     70.442740  1.273002e+05    6313.584411  5.480092e+04
min      -51.796300   -135.000000  0.000000e+00       0.000000  0.000000e+00
25%        7.873054    -15.310100  4.000000e+00       0.000000  0.000000e+00
50%       23.634500     21.745300  1.680000e+02       2.000000  2.900000e+01
75%       41.204380     80.771797  1.518250e+03      30.000000  6.660000e+02
max       71.706900    178.065000  4.290259e+06  148011.000000  1.846641e+06

In [43]:
# obtendo alguns dados interessantes sobre as colunas. 
# apenas os dados da Province/State estão faltando. 14664/49068 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Province/State  14664 non-null  object 
 1   Country/Region  49068 non-null  object 
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object 
 5   Confirmed       49068 non-null  int64  
 6   Deaths          49068 non-null  int64  
 7   Recovered       49068 non-null  int64  
 8   WHO Region      49068 non-null  object 
dtypes: float64(2), int64(3), object(4)
memory usage: 3.4+ MB


In [46]:
# tratando valores nulos, as opção seriam: remover as linhas que não estão completas ou preeches os campos. 
# para essa análise decidi preecher os campos para não perder dados 
# a função fillna() preeche os dados faltates, caso a opção adotada fosse remover, utilizar o dropna()

df.fillna('NA', inplace=True) 

In [47]:
#verificando o dataframe mais uma vez, agora com os dados preechidos 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Province/State  49068 non-null  object 
 1   Country/Region  49068 non-null  object 
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object 
 5   Confirmed       49068 non-null  int64  
 6   Deaths          49068 non-null  int64  
 7   Recovered       49068 non-null  int64  
 8   WHO Region      49068 non-null  object 
dtypes: float64(2), int64(3), object(4)
memory usage: 3.4+ MB


In [58]:
# Aqui, vou agrupar as informações relacionadas a 'confirmado', 'morte', e 'recuperado', de acordo com os países

df2 = df.groupby('Country/Region')[['Country/Region','Confirmed', 'Deaths', 'Recovered']].sum().reset_index()
df2

Country/Region  Confirmed  Deaths  Recovered
0           Afghanistan    1936390   49098     798240
1               Albania     196702    5708     118877
2               Algeria    1179755   77972     755897
3               Andorra      94404    5423      69074
4                Angola      22662    1078       6573
..                  ...        ...     ...        ...
182  West Bank and Gaza     233461    1370      61124
183      Western Sahara        901      63        648
184               Yemen      67180   17707      23779
185              Zambia     129421    2643      83611
186            Zimbabwe      50794     881      12207

[187 rows x 4 columns]

In [61]:
# Ordenando informações por número de mortes do maior para o menor 

df_death = df2.sort_values(by='Deaths', ascending=False)
df_death

Country/Region  Confirmed    Deaths  Recovered
173              US  224345948  11011411   56353416
177  United Kingdom   26748587   3997775     126217
23           Brazil   89524967   3938034   54492873
85            Italy   26745145   3707717   15673910
61           France   21210926   3048524    7182115
..              ...        ...       ...        ...
19           Bhutan       4971         0       2838
114        Mongolia      16999         0       9902
168     Timor-Leste       2487         0          0
148      Seychelles       3977         0       1247
68        Greenland       1507         0       1372

[187 rows x 4 columns]